baseURL = 'https://vennerstrom.se/'
locale = 'en-us'
title = 'Victor Vennerström'

disableKinds = ['taxonomy', 'term']
cleanDestinationDir = true

[params]
  author = 'Victor Vennerström'
  authorURL = 'https://vennerstrom.se'
  blogInitial = 6
  workInitial = 8

[permalinks]
  blog = '/:slug'
  work = '/:slug'

[outputFormats]
  [outputFormats.PostsJSON]
    mediaType = 'application/json'
    baseName = 'posts'
    isPlainText = true
    notAlternative = true

[outputs]
  home = ['HTML', 'PostsJSON']
